name: tmate session
on: [workflow_dispatch]

jobs:
  tmate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Start tmate session
        uses: mxschmitt/action-tmate@v4
